// Byte-parity test: taiwan-plates.js output vs the shipped plate .scad
// files under taiwan-1992/output/ (originally generated by the Python
// pipeline's scripts/build_plate_scad.py; comment lines updated since) and
// the 新式 (2012) plates under taiwan-2012/output/.
//
//   node tools/tests/test_taiwan_plates.mjs
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { Plates } from "../../taiwan-plates.js";
import { GLYPH_SETTINGS } from "../taiwan_glyph_source.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..", "..");

const traces = JSON.parse(readFileSync(join(root, "taiwan-glyphs", "traces.json"), "utf8"));
const opts = {
  chars: [...GLYPH_SETTINGS.chars],
  svgW: GLYPH_SETTINGS.svgW,
  svgH: GLYPH_SETTINGS.svgH,
  moduleName: (char) => `${GLYPH_SETTINGS.modulePrefix}${char}`,
  sampleOpts: () => GLYPH_SETTINGS,
};

const cases = [
  ...Plates.SPECS.map((spec) => ({ spec, dir: "taiwan-1992" })),
  ...Plates.SPECS_2012.map((spec) => ({ spec, dir: "taiwan-2012" })),
];

let fail = 0;

if (Plates.DEFAULT_HEADER.includes("License: CC-Attribution-ShareAlike")) {
  console.log("PASS default model license is CC-Attribution-ShareAlike");
} else {
  fail += 1;
  console.log("FAIL default model license is not CC-Attribution-ShareAlike");
}

{
  const outputs = cases.map(({ spec }) => Plates.buildPlateScad(spec, traces, opts));
  const sharedChecks = [
    '"Z","-","1"',
    'else if (c == "-") glyph_dash();',
    "square([dot_w / glyph_scale, dot_h / glyph_scale], center = true);",
  ];
  if (outputs.every((out) => sharedChecks.every((text) => out.includes(text)))) {
    console.log("PASS dash matches each plate's fixed separator size");
  } else {
    fail += 1;
    console.log("FAIL dash does not match each plate's fixed separator size");
  }
}

for (const { spec, dir } of cases) {
  const actual = Plates.buildPlateScad(spec, traces, opts);
  const expected = readFileSync(join(root, dir, "output", spec.filename), "utf8");
  if (actual === expected) {
    console.log(`PASS ${spec.filename} (${actual.length} bytes, byte-identical)`);
  } else {
    fail += 1;
    const a = actual.split("\n");
    const e = expected.split("\n");
    for (let i = 0; i < Math.max(a.length, e.length); i += 1) {
      if (a[i] !== e[i]) {
        console.log(`FAIL ${spec.filename} first diff at line ${i + 1}:`);
        console.log(`  expected: ${JSON.stringify((e[i] || "").slice(0, 120))}`);
        console.log(`  actual:   ${JSON.stringify((a[i] || "").slice(0, 120))}`);
        break;
      }
    }
  }
}

// The 300x150 large-heavy model is one download button with an unadorned
// label; plate colour remains selectable inside the OpenSCAD Customizer.
{
  const spec = Plates.SPECS_2012.find(
    (item) => item.filename === "taiwan 2012 license plate(large heavy motorcycle).scad"
  );
  const expected = {
    label: "大型重機",
    size: [300, 150],
    holes: [
      [69, 126, 22, 12, 6],
      [209, 126, 22, 12, 6],
    ],
    plateTypes: [
      ["紅牌", "#FF0000", "#FFFFFF"],
      ["黃牌", "#FFFF00", "#000000"],
    ],
  };
  const actual = spec && {
    label: spec.label,
    size: [spec.plateW, spec.plateH],
    holes: spec.holes2012,
    plateTypes: spec.plateTypes,
  };
  if (JSON.stringify(actual) === JSON.stringify(expected)) {
    console.log("PASS 2012 large-heavy size, holes, colours and button label");
  } else {
    fail += 1;
    console.log("FAIL 2012 large-heavy spec invariant");
  }
}

// OpenSCAD string escaping + arbitrary-Unicode charsets: " and \ must emit
// valid dispatch lines (c == "\"") / (c == "\\"), never a bare
// quote/backslash, and non-ASCII chars pass through with slug module names.
{
  const slug = (char) =>
    /^[A-Z0-9]$/.test(char) ? char : "u" + char.codePointAt(0).toString(16).toUpperCase();
  const escOpts = {
    ...opts,
    chars: [...opts.chars, '"', "\\", "中"],
    moduleName: (char) => `glyph_2012_${slug(char)}`,
  };
  const escTraces = { ...traces, '"': traces.A, "\\": traces.A, "中": traces.A };
  const out = Plates.buildPlateScad(Plates.SPECS[0], escTraces, escOpts);
  const expectedLines = [
    '    else if (c == "\\"") glyph_2012_u22();',
    '    else if (c == "\\\\") glyph_2012_u5C();',
    '    else if (c == "中") glyph_2012_u4E2D();',
  ];
  for (const line of expectedLines) {
    if (out.includes(line)) {
      console.log(`PASS scad-escape ${JSON.stringify(line.trim())}`);
    } else {
      fail += 1;
      console.log(`FAIL scad-escape: missing ${JSON.stringify(line)}`);
    }
  }
}

process.exit(fail ? 1 : 0);
